<?php
/**
 * @file
 * GSB Text Equivalent, provides readable text version of website assets.
 */

/**
 * Implements hook_menu().
 */
function gsb_text_equivalent_menu() {
  $items = array();
  $items['text-equivalent/%/%'] = array(
    'description' => 'View Text Equivalent.',
    'page callback' => 'gsb_text_equivalent_view_text_equivalent',
    'page arguments' => array(1, 2),
    'access arguments' => array('access content'),
  );
  return $items;
}

/**
 * Callback function.
 */
function gsb_text_equivalent_view_text_equivalent($type, $id) {
  $entity = entity_load($type, array($id));
  // Add CSS.
  drupal_add_css(drupal_get_path('theme', 'gsb_theme') . '/css/style.css');
  $display = array('label' => 'hidden');
  return field_view_field($type, $entity[$id], 'field_text_equivalent', $display);
}

/**
 * Implements hook_custom_theme().
 */
function gsb_text_equivalent_custom_theme() {
  // Set the theme to stark.
  $args = explode('/', current_path());
  if ($args[0] == 'text-equivalent') {
    return 'stark';
  }
}
/**
 * Implements hook_page_alter().
 */
function gsb_text_equivalent_page_alter(&$page) {
  // Hide all the region except content for clean html.
  $args = explode('/', current_path());
  if ($args[0] == 'text-equivalent') {
    foreach (element_children($page) as $region) {
      if ($region != 'content') {
        unset($page[$region]);
      }
    }
  }

  // Add the metatag title for the text equivalent page.
  if (!empty($page['content']['system_main']['#object']->field_title['und'][0])) {
    $title = $page['content']['system_main']['#object']->field_title['und'][0]['safe_value'];
    drupal_set_title($title);
    $title_part2 = $page['content']['metatags']['global']['title']['#attached']['metatag_set_preprocess_variable'][0][2];
    if ($title_part2 != "") {
      $title_part2 = str_replace('Home', '', $title_part2);
    }
    $page['content']['metatags']['global']['title']['#attached']['metatag_set_preprocess_variable'][0][2] = $title . ' ' . $title_part2;
  }
  elseif (!empty($page['content']['system_main']['#bundle']) && $page['content']['system_main']['#bundle'] == 'image') {
    $title = $page['content']['system_main']['#object']->title;
    drupal_set_title($title);
    $title_part2 = $page['content']['metatags']['global']['title']['#attached']['metatag_set_preprocess_variable'][0][2];
    if ($title_part2 != "") {
      $title_part2 = str_replace('Home', '', $title_part2);
    }
    $page['content']['metatags']['global']['title']['#attached']['metatag_set_preprocess_variable'][0][2] = $title . ' ' . $title_part2;
  }
  elseif (empty($page['content']['system_main']['#object']->field_title['und'][0])) {
    if (!empty($page['content']['system_main']['#bundle']) && $page['content']['system_main']['#bundle'] == 'resource_image') {
      drupal_set_title('');
      $title_part2 = $page['content']['metatags']['global']['title']['#attached']['metatag_set_preprocess_variable'][0][2];
      $page['content']['metatags']['global']['title']['#attached']['metatag_set_preprocess_variable'][0][2] = substr($title_part2, 6);;
    }
  }
}
